<?xml version="1.0" encoding="UTF-8"?>
<!--
    Renders sitemap.xml as a readable table in a browser while leaving it
    valid XML for crawlers. Without this a visitor clicking "XML sitemap"
    gets a wall of raw markup, or a download prompt.
-->
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9">

  <xsl:output method="html" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="robots" content="noindex,follow"/>
        <title>XML Sitemap — Ahsan Nawaz</title>
        <style>
          :root{--g:#15803d;--gd:#14532d;--ink:#0f172a;--mut:#64748b;--line:#e2e8f0;--bg:#f8fafc}
          *{box-sizing:border-box;margin:0;padding:0}
          body{background:var(--bg);color:var(--ink);
               font:15px/1.6 'DM Sans',system-ui,-apple-system,sans-serif;padding:2rem 1rem}
          .wrap{max-width:1000px;margin:0 auto}
          header{margin-bottom:1.5rem}
          h1{font-size:1.6rem;letter-spacing:-.02em;margin-bottom:.35rem}
          .sub{color:var(--mut);font-size:.9rem}
          .sub a{color:var(--g)}
          .count{display:inline-block;background:#f0fdf4;color:var(--g);border:1px solid rgba(21,128,61,.2);
                 border-radius:999px;padding:.25rem .7rem;font-size:.8rem;font-weight:600;margin-top:.7rem}
          table{width:100%;border-collapse:collapse;background:#fff;border:1px solid var(--line);
                border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(15,23,42,.07)}
          th{background:var(--gd);color:#fff;text-align:left;padding:.75rem 1rem;
             font-size:.72rem;letter-spacing:.08em;text-transform:uppercase}
          td{padding:.75rem 1rem;border-top:1px solid var(--line);font-size:.88rem;vertical-align:top}
          tr:hover td{background:#f0fdf4}
          td a{color:var(--g);text-decoration:none;word-break:break-all}
          td a:hover{text-decoration:underline}
          .num{color:var(--mut);width:3rem}
          .meta{color:var(--mut);white-space:nowrap}
          footer{margin-top:1.5rem;color:var(--mut);font-size:.82rem}
          footer a{color:var(--g)}
          @media(max-width:640px){.hide{display:none}td,th{padding:.6rem .7rem}}
        </style>
      </head>
      <body>
        <div class="wrap">
          <header>
            <h1>XML Sitemap</h1>
            <p class="sub">
              This file lists every page for search engines. Looking for the readable
              version? <a href="/sitemap">Browse the sitemap page</a>.
            </p>
            <span class="count">
              <xsl:value-of select="count(s:urlset/s:url)"/> URLs
            </span>
          </header>

          <table>
            <tr>
              <th class="num">#</th>
              <th>URL</th>
              <th class="hide">Last modified</th>
              <th class="hide">Change frequency</th>
              <th class="hide">Priority</th>
            </tr>
            <xsl:for-each select="s:urlset/s:url">
              <tr>
                <td class="num"><xsl:value-of select="position()"/></td>
                <td>
                  <a href="{s:loc}"><xsl:value-of select="s:loc"/></a>
                </td>
                <td class="meta hide"><xsl:value-of select="substring(s:lastmod,1,10)"/></td>
                <td class="meta hide"><xsl:value-of select="s:changefreq"/></td>
                <td class="meta hide"><xsl:value-of select="s:priority"/></td>
              </tr>
            </xsl:for-each>
          </table>

          <footer>
            Generated by <a href="/">ahsannawaz.dev</a> — submit this URL in Google Search Console.
          </footer>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
